CREATE TABLE Customer(
Id INT PRIMARY KEY AUTO_INCREMENT,
PersNo VARCHAR(13) UNIQUE NOT NULL,
Password VARCHAR(40) NOT NULL,
Firstname VARCHAR(64) NOT NULL,
Lastname VARCHAR(64) NOT NULL,
Email VARCHAR(64)
);

CREATE TABLE Product(
Id INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(64) NOT NULL,
NumberOfTokens INT
);

CREATE TABLE Agreement(
Id INT PRIMARY KEY AUTO_INCREMENT,
CustomerId INT,
ProductId INT,
AgreementSignedDate DATE,
AgreementSignedTime TIME
);

CREATE TABLE CustomerInfo(
Id INT PRIMARY KEY AUTO_INCREMENT,
CustomerId INT,
MaritalStatusId INT,
Children BIT,
AccommodationId INT
);

ALTER TABLE Agreement ADD FOREIGN KEY (CustomerId) REFERENCES Customer(Id);
ALTER TABLE Agreement ADD FOREIGN KEY (ProductId) REFERENCES Product(Id);
ALTER TABLE CustomerInfo ADD FOREIGN KEY (CustomerId) REFERENCES Customer(Id);

CREATE TABLE MaritalStatus(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(50)
);

CREATE TABLE Accommodation(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(50)
);

ALTER TABLE CustomerInfo ADD FOREIGN KEY (MaritalStatusId) REFERENCES MaritalStatus(Id);
ALTER TABLE CustomerInfo ADD FOREIGN KEY (AccommodationId) REFERENCES Accommodation(Id);