CREATE TABLE Customer(
Id INT PRIMARY KEY AUTO_INCREMENT,
persNo VARCHAR(13) UNIQUE NOT NULL,
password VARCHAR(40) NOT NULL,
firstName VARCHAR(64) NOT NULL,
lastName VARCHAR(64) NOT NULL,
email VARCHAR(64)
);

CREATE TABLE Product(
Id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(64) NOT NULL,
numberOfTokens INT
);

CREATE TABLE Agreement(
Id INT AUTO_INCREMENT PRIMARY KEY,
customerId INT NOT NULL FOREIGN KEY REFERENCES Customer(Id),
productId INT NOT NULL FOREIGN KEY REFERENCES Product(Id),
agreementSigned TIMESTAMP
);