CREATE TABLE Customer(
Id INT PRIMARY KEY AUTO_INCREMENT,
persNo VARCHAR(13) UNIQUE NOT NULL,
password VARCHAR(40) NOT NULL,
firstName VARCHAR(64) NOT NULL,
lastName VARCHAR(64) NOT NULL,
email VARCHAR(64)
);
